[
    {"name": "CALIPER22", "town": "town", "nation": "No Nation", "rank": "Mayor"},
    {"name": "CanYouNosh", "town": "Oblivion", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "Strafeduck",
        "town": "Oblivion",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "ResetCombo",
        "town": "Oblivion",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {"name": "isac__", "town": "Who_Was_In_Paris", "nation": "Britan", "rank": "Mayor"},
    {
        "name": "_Tomast045",
        "town": "The_Danish_Republic",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_ItzAnders5591",
        "town": "The_Danish_Republic",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "Tofuroki",
        "town": "pogtopia",
        "nation": "Pogtopian_Brazil",
        "rank": "Nation Leader",
    },
    {
        "name": "_LucasPlxys",
        "town": "pogtopia",
        "nation": "Pogtopian_Brazil",
        "rank": "Resident",
    },
    {
        "name": "_Tofuroki",
        "town": "pogtopia",
        "nation": "Pogtopian_Brazil",
        "rank": "Resident",
    },
    {
        "name": "wollemwierts",
        "town": "pogtopia",
        "nation": "Pogtopian_Brazil",
        "rank": "Resident",
    },
    {
        "name": "_Mrcl0D",
        "town": "pogtopia",
        "nation": "Pogtopian_Brazil",
        "rank": "Resident",
    },
    {
        "name": "_CrabbyBog271804",
        "town": "pogtopia",
        "nation": "Pogtopian_Brazil",
        "rank": "Resident",
    },
    {
        "name": "NightMare6906",
        "town": "pogtopia",
        "nation": "Pogtopian_Brazil",
        "rank": "Resident",
    },
    {
        "name": "pattie97",
        "town": "pogtopia",
        "nation": "Pogtopian_Brazil",
        "rank": "Resident",
    },
    {
        "name": "TheGoatsMilk1",
        "town": "The_World_Order",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "KindaMrPancake", "town": "Scripps", "nation": "Cuba", "rank": "Mayor"},
    {
        "name": "MimiC2013",
        "town": "new-phantopia",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "potato_bath",
        "town": "Dark_Reunion",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "GG_XD_Gaming",
        "town": "The_Pros",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "JrIsGod9988",
        "town": "The_Pros",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_airrox_",
        "town": "The_Pros",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_DingersOnly1127",
        "town": "The_Pros",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_A6oot273abc123",
        "town": "The_three_Kings",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "_ItzzMilky_",
        "town": "The_three_Kings",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {"name": "Polish_Cowwwww", "town": "perth", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "starwarsnerd353",
        "town": "perth",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {"name": "ironsword88", "town": "perth", "nation": "No Nation", "rank": "Resident"},
    {
        "name": "Purple1bacon",
        "town": "perth",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {"name": "superBOyO8", "town": "perth", "nation": "No Nation", "rank": "Resident"},
    {"name": "Ryano_0", "town": "perth", "nation": "No Nation", "rank": "Resident"},
    {
        "name": "MuddledGecko991",
        "town": "Sicily",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "TorndMc",
        "town": "Sicily",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_notkousuke",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Nation Leader",
    },
    {
        "name": "_Takuwan1224",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "_anvilol",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "_yamaimo11924",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "_VinyDoubloon86",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "_KATANA1934",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "_Hokoke2320Akst",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "_Shirasu24",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "_arubabi927",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "_Haru042356",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "_rain612",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "Giga_Whithers",
        "town": "U.S_TWMC",
        "nation": "zawamushi_Empire",
        "rank": "Resident",
    },
    {
        "name": "Bunglefunk_",
        "town": "Gary",
        "nation": "Midwest_USA",
        "rank": "Nation Leader",
    },
    {"name": "_Minktail", "town": "Gary", "nation": "Midwest_USA", "rank": "Resident"},
    {
        "name": "ManicFlea840",
        "town": "Gary",
        "nation": "Midwest_USA",
        "rank": "Resident",
    },
    {
        "name": "PowerfulPepper1",
        "town": "Gary",
        "nation": "Midwest_USA",
        "rank": "Resident",
    },
    {"name": "ItsJuley", "town": "Gary", "nation": "Midwest_USA", "rank": "Resident"},
    {
        "name": "_ciel0beats",
        "town": "Gary",
        "nation": "Midwest_USA",
        "rank": "Resident",
    },
    {
        "name": "xxcharlottee",
        "town": "Gary",
        "nation": "Midwest_USA",
        "rank": "Resident",
    },
    {
        "name": "KatzPlayzGamez1",
        "town": "Gary",
        "nation": "Midwest_USA",
        "rank": "Resident",
    },
    {"name": "cereal0057", "town": "Gary", "nation": "Midwest_USA", "rank": "Resident"},
    {
        "name": "wonder_fairy",
        "town": "Gary",
        "nation": "Midwest_USA",
        "rank": "Resident",
    },
    {"name": "Andrakko", "town": "Gary", "nation": "Midwest_USA", "rank": "Resident"},
    {"name": "_Lem0nCatt", "town": "Gary", "nation": "Midwest_USA", "rank": "Resident"},
    {
        "name": "_FacedNebula1325",
        "town": "Gary",
        "nation": "Midwest_USA",
        "rank": "Resident",
    },
    {"name": "_Cursed95", "town": "Trkiye", "nation": "No Nation", "rank": "Mayor"},
    {"name": "_PawlPall", "town": "Trkiye", "nation": "No Nation", "rank": "Resident"},
    {
        "name": "_crysisss9868",
        "town": "Trkiye",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_MrSantex1851",
        "town": "Trkiye",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_ZexIust_M4",
        "town": "Trkiye",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_Skorzz3496",
        "town": "Trkiye",
        "nation": "No Nation",
        "rank": "Resident",
        "x": 6476,
        "y": 91,
        "z": -8153,
        "isUnderground": False,
        "nickname": "_Skorzz3496",
    },
    {
        "name": "_BatedBranch9938",
        "town": "Groundville",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Guenther_007567",
        "town": "Groundville",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Holly0456",
        "town": "Groundville",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Chipskruemel7",
        "town": "Groundville",
        "nation": "Severny",
        "rank": "Mayor",
    },
    {
        "name": "Kekskruemel7",
        "town": "Groundville",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_CMG_Hashirama",
        "town": "Groundville",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Fire254600",
        "town": "Groundville",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Thermosifounas",
        "town": "mushroomville",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "st1nning",
        "town": "mushroomville",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "szlifierkademon",
        "town": "Atlanta",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "itsolczixx",
        "town": "Atlanta",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_AgedMonkey75682",
        "town": "south_Africa",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "BOT19", "town": "wedza", "nation": "No Nation", "rank": "Mayor"},
    {"name": "z0mbie__", "town": "PhnomPenh", "nation": "Vietnam", "rank": "Mayor"},
    {
        "name": "chil123",
        "town": "Tamaulipas",
        "nation": "Nueva_Castilla",
        "rank": "Mayor",
    },
    {
        "name": "_foxygammer158",
        "town": "Tamaulipas",
        "nation": "Nueva_Castilla",
        "rank": "Resident",
    },
    {
        "name": "_Elzombito58",
        "town": "Tamaulipas",
        "nation": "Nueva_Castilla",
        "rank": "Resident",
    },
    {
        "name": "BOT17",
        "town": "Republic_of_Ukraine",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "AKHISARLI",
        "town": "Moria",
        "nation": "Greater_Armenia",
        "rank": "Nation Leader",
    },
    {
        "name": "Sennnnnnnnnnnnn",
        "town": "Chinese",
        "nation": "Rev-China",
        "rank": "Mayor",
    },
    {"name": "m0o0o0lly", "town": "Chinese", "nation": "Rev-China", "rank": "Resident"},
    {"name": "OGAsterrr", "town": "NZpros", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "EmmyyyssssOG",
        "town": "NZpros",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Buquibux",
        "town": "Galiza",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "Djinsomnia",
        "town": "The_Friend_Zone",
        "nation": "Cool_Runnings",
        "rank": "Nation Leader",
    },
    {
        "name": "Sorty__",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Nation Leader",
    },
    {
        "name": "ZombieBrine1309",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "frank33cy",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "GrainOfBread",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "_vgamerXD3466",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "AngelThePotato",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "_Milan201203",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "_Poponax",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "DannyNgo123",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "aceofspadez142",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "cdgJoseph",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "transkid_",
        "town": "Bigote_Verde",
        "nation": "Antarctica",
        "rank": "Resident",
    },
    {
        "name": "Landyzhirui",
        "town": "Qiongzhou",
        "nation": "Rev-China",
        "rank": "Mayor",
    },
    {
        "name": "Event_CpTreLemot",
        "town": "Qiongzhou",
        "nation": "Rev-China",
        "rank": "Resident",
    },
    {
        "name": "TheodorHerzl",
        "town": "Constantinople",
        "nation": "Byzantine_Empire",
        "rank": "Nation Leader",
    },
    {
        "name": "DemosekV",
        "town": "Constantinople",
        "nation": "Byzantine_Empire",
        "rank": "Resident",
    },
    {"name": "BOT1", "town": "ciel", "nation": "Chile", "rank": "Mayor"},
    {"name": "Foroei", "town": "Malta", "nation": "Spanish_Republic", "rank": "Mayor"},
    {
        "name": "Vlad_HD1234",
        "town": "Animetown",
        "nation": "Asia",
        "rank": "Nation Leader",
    },
    {"name": "buckethatdud", "town": "CB", "nation": "Angola", "rank": "Nation Leader"},
    {"name": "_CerealWig204460", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "dysLexic06", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_bean2689", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_byvee2500", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "mery12300", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_buckett1855", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_dombfg57841", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_ConstantPoet243", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_liltoottoot1", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_datbingbop", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "AhmadAlNaser", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "SCREAMFORSKY", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "ElitePandaz", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Benhaard", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Khalgun_420", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "icyka", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "123djv", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "craftyminer007", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "OsviSobarzoc", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "x_emily_x", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Siminator2002", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "sonothousandrats", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_dottie2152", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Hynki", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "LouisonObriot", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "jimbobdixon", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "jango27", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "yoongibaldhead", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "CASHBALLERR", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Mr_sandman999", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "DoosinShawn", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Tolpen", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "westcott1234", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Still1foot", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "nBoi", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Calibercale45", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Esther27", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "bogdanov_X", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "orientalduck", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "BeastBobby03", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "AidanDavid05", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "SlaveOfCiel", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "MexicanBeaulo", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "rustte", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "snaixl", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "DoctorBena", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "mkerr", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "tftboris", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_sippingontea452", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_Rxze_VISION", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "LukeHolden", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "pankakewookie", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "leopard_spirit", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "MurilinHN", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Kiwi3goist4", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "OliviaSundberg", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Urielle9158", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_ireniee", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "kttremain", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "BombTheMedics", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Darofo", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "aidzoid123", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "miastozychlin", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "xenosmccloud", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "mortennHS", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Lucas8pro123", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "JadenIsBack101", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "EnamelLight", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Scarlet_07", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "CashCarti_2900", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "TheMasterWK02", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "aalibunny310", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Zeraine", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "joey3423423", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "JEMZU", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "rohan28", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Kite56", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Serasine", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "PurpleHayley", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Joshi_Willared", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "atxgl", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Andreww345", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "aerilis2", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "AFlyingKatana", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Vortex_Boss", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "MaxSundqvist", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "BlacktoothB", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "GeeTee800", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "yopplstomper58", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "evananthem", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "titione482", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "DandayXD", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "minecraftpanda6", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Tris813", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "OnGodNoCapJackyy", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "kittylover4850", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "jigglypiglets6t9", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "asfiara", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "thebettereven", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "schoolshoote", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "NWRWS01", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "oldvisions", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Elgard", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "IBSMercenary", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Toriality", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "slinkycurtis", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "yux_01", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Tlakuash", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Indrawn", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Derpleson", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "TacoMunchers", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "bootymuncherrr", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "BroncosoJr", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "_vladut_11", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Wonderblacky", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Vampurp", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "binguspp1", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Prischilla", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "LudovicoV933", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "P4rD0nM3", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "kalabmorris", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Pezbi", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "pego_o", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Malonensunrise", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "AreLuggNesROFLE", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Maheux03", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Swagjavob", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "ikonnic", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Carrotnox", "town": "CB", "nation": "Angola", "rank": "Resident"},
    {"name": "Eisen_Master", "town": "eisen", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "Marcel_Radler",
        "town": "eisen",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "MilkCookiesX",
        "town": "Siberian",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "BazinUwU",
        "town": "Islas_Malvinas",
        "nation": "Argentina",
        "rank": "Nation Leader",
    },
    {
        "name": "_SFxT_Bravo_911",
        "town": "irnbruto2",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {"name": "meeracat", "town": "ponyo", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "_Skorpy12",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Mayor",
    },
    {
        "name": "_Paaaulino",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "alexmunozz",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "Bochrzen_22",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Alex12900832974",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "NoahJBB",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "vlassiefishy",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "Ami_Stepien",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "ghostess123",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_sarasasha225",
        "town": "beach_bay",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {"name": "ILO_K", "town": "Tempest", "nation": "Severny", "rank": "Resident"},
    {"name": "FireFFW22", "town": "Tempest", "nation": "Severny", "rank": "Resident"},
    {"name": "_Rezap5412", "town": "Tempest", "nation": "Severny", "rank": "Resident"},
    {"name": "Rescreamer", "town": "Tempest", "nation": "Severny", "rank": "Resident"},
    {
        "name": "_Lindaminda6472",
        "town": "Tempest",
        "nation": "Severny",
        "rank": "Resident",
    },
    {"name": "WurstKoenig", "town": "Tempest", "nation": "Severny", "rank": "Resident"},
    {"name": "StulenKaiser", "town": "Tempest", "nation": "Severny", "rank": "Mayor"},
    {"name": "aly__999", "town": "Tempest", "nation": "Severny", "rank": "Resident"},
    {
        "name": "DattelDattelig",
        "town": "Tempest",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "todesschn1tzel",
        "town": "Tempest",
        "nation": "Severny",
        "rank": "Resident",
    },
    {"name": "ArneNo2007", "town": "Tempest", "nation": "Severny", "rank": "Resident"},
    {"name": "BOT9", "town": "retirement_home", "nation": "No Nation", "rank": "Mayor"},
    {"name": "Hopkins14", "town": "Veritas", "nation": "No Nation", "rank": "Mayor"},
    {"name": "alinvq", "town": "Aria", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "eellioz",
        "town": "AngelDust",
        "nation": "Venezuela",
        "rank": "Nation Leader",
    },
    {"name": "_B3ans0", "town": "AngelDust", "nation": "Venezuela", "rank": "Resident"},
    {
        "name": "BOT14",
        "town": "Vacation_Island",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "BOT13",
        "town": "antarctic_empire",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "Mirindasaft",
        "town": "New_balkans",
        "nation": "Turkish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "sydweee",
        "town": "yellow_barrel_desk",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "trrin",
        "town": "yellow_barrel_desk",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "fjunior_0911",
        "town": "birmingham",
        "nation": "Britan",
        "rank": "Resident",
    },
    {
        "name": "ChromeCrits",
        "town": "birmingham",
        "nation": "Britan",
        "rank": "Resident",
    },
    {"name": "suuv", "town": "birmingham", "nation": "Britan", "rank": "Resident"},
    {"name": "Szymqn", "town": "birmingham", "nation": "Britan", "rank": "Resident"},
    {"name": "idk69420", "town": "birmingham", "nation": "Britan", "rank": "Resident"},
    {"name": "penqX", "town": "birmingham", "nation": "Britan", "rank": "Resident"},
    {"name": "Connexorr", "town": "birmingham", "nation": "Britan", "rank": "Resident"},
    {
        "name": "clappedcookie",
        "town": "birmingham",
        "nation": "Britan",
        "rank": "Mayor",
    },
    {"name": "Blissterz", "town": "birmingham", "nation": "Britan", "rank": "Resident"},
    {"name": "BOT12", "town": "GoodyTown", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "_GabbyRix14",
        "town": "Marawi",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {"name": "BOT20", "town": "Marawi", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "LivingPepsiCan",
        "town": "Shellson_Island",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "DarthValk", "town": "Florida", "nation": "Midwest_USA", "rank": "Mayor"},
    {
        "name": "Kittyyyyyyyyyy",
        "town": "Leaf_Village",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "_WalnutBreak58",
        "town": "Sapporo",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "_CamLeBoss03", "town": "Milka", "nation": "Morocco", "rank": "Resident"},
    {"name": "DracoFire28YT", "town": "Milka", "nation": "Morocco", "rank": "Resident"},
    {
        "name": "Ademcake7777",
        "town": "Milka",
        "nation": "Morocco",
        "rank": "Nation Leader",
    },
    {
        "name": "Jelle261007",
        "town": "Vicenza",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "_Sunt_mic",
        "town": "Vicenza",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_djdabest2000",
        "town": "Vicenza",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "Kittenqueen51",
        "town": "Vicenza",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_Christophe2457",
        "town": "Vicenza",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "TryH4r9Gavin",
        "town": "Vicenza",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "yukiJP_",
        "town": "Vicenza",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "FOOD4LIFE8505",
        "town": "Vicenza",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "OLIfant_toettoet",
        "town": "Vicenza",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_Jelle2610",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_MildGolf6279233",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "Sebis_YT",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "YouChoir",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "KMHunter",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_Adammsvania",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_zZTheNoHand",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "szymek91",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "SlayerSlaysG",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_Jess9469",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_ToppinTomato79",
        "town": "Napoli",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "AppleJackZac",
        "town": "New_Mendez",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "Soggystarfish6",
        "town": "New_Mendez",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_dalia2224life",
        "town": "Bagel_Town",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "Borstiii",
        "town": "Earthoon",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "_KaputPluto79183",
        "town": "Earthoon",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_LeasingAunt5011",
        "town": "Springfield",
        "nation": "4.1ReadRules",
        "rank": "Mayor",
    },
    {
        "name": "Moaked",
        "town": "Springfield",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {
        "name": "_BigSoggySheep",
        "town": "Kattegat",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "Ky_Loren_zo", "town": "Recruta", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "_WaryTrack476342",
        "town": "Germany",
        "nation": "Prussia",
        "rank": "Nation Leader",
    },
    {
        "name": "Ex_Sins",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Nation Leader",
    },
    {"name": "YungzExE", "town": "no", "nation": "4.1ReadRules", "rank": "Resident"},
    {
        "name": "Skylah_peters",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {
        "name": "cj_is_beast_1",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {
        "name": "V_Ambersphere",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {"name": "Duck______x", "town": "no", "nation": "4.1ReadRules", "rank": "Resident"},
    {
        "name": "RiotPanda123",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {
        "name": "WillisvStrom",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {"name": "_NelJelvet1", "town": "no", "nation": "4.1ReadRules", "rank": "Resident"},
    {
        "name": "_EmeraldCyan4638",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {"name": "Miggy12Ten", "town": "no", "nation": "4.1ReadRules", "rank": "Resident"},
    {
        "name": "redpandanico",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {"name": "DarkMando", "town": "no", "nation": "4.1ReadRules", "rank": "Resident"},
    {"name": "ShroomBee4", "town": "no", "nation": "4.1ReadRules", "rank": "Resident"},
    {
        "name": "_Eaglely7466",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {"name": "ogrektaa09", "town": "no", "nation": "4.1ReadRules", "rank": "Resident"},
    {"name": "MrAppelsap", "town": "no", "nation": "4.1ReadRules", "rank": "Resident"},
    {"name": "_kover_up", "town": "no", "nation": "4.1ReadRules", "rank": "Resident"},
    {
        "name": "_Grapewrld123",
        "town": "no",
        "nation": "4.1ReadRules",
        "rank": "Resident",
    },
    {"name": "kikoleite23", "town": "The_Boys", "nation": "Malaysia", "rank": "Mayor"},
    {"name": "BLZsonic", "town": "The_Boys", "nation": "Malaysia", "rank": "Resident"},
    {
        "name": "Penguinman1",
        "town": "Penguin_Empire",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "Mordred_FATE",
        "town": "Penguin_Empire",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "sensei1fbeure",
        "town": "Venice",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "JJGBF",
        "town": "Watertown",
        "nation": "Malaysia",
        "rank": "Nation Leader",
    },
    {"name": "Grsy", "town": "New_York", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "_CloudsMay",
        "town": "Gutensberg",
        "nation": "Klaudian_Republic",
        "rank": "Mayor",
    },
    {
        "name": "KaloyanPetrov1",
        "town": "Gutensberg",
        "nation": "Klaudian_Republic",
        "rank": "Resident",
    },
    {
        "name": "S0phieRenae",
        "town": "Communism_of_Asia",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "_swagyreva",
        "town": "Communism_of_Asia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "zviperlite",
        "town": "Communism_of_Asia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Kidpossible911",
        "town": "ChungusTown",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "Swager129",
        "town": "ChungusTown",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "MelinaCraft17",
        "town": "ChungusTown",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_CringGuy420",
        "town": "Memphis",
        "nation": "Memphis",
        "rank": "Nation Leader",
    },
    {
        "name": "ar3ly82",
        "town": "Jalta",
        "nation": "Ottoman_Empire",
        "rank": "Resident",
    },
    {"name": "imbatmain", "town": "Jalta", "nation": "Ottoman_Empire", "rank": "Mayor"},
    {
        "name": "Blue_ScorpionFIN",
        "town": "Helsinki",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "g0d_4lex", "town": "Eraldopoli", "nation": "No Nation", "rank": "Mayor"},
    {"name": "iLixer", "town": "Monteria", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "EuGaming",
        "town": "AnglerTown",
        "nation": "Madagascar_C.U.L",
        "rank": "Mayor",
    },
    {
        "name": "Kecks_Dose",
        "town": "AnglerTown",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "thnead",
        "town": "Shroom_Village",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "_Skep1247", "town": "Kyiv", "nation": "Ukraine", "rank": "Mayor"},
    {"name": "_kingPeAaa", "town": "Kyiv", "nation": "Ukraine", "rank": "Resident"},
    {"name": "KDb_Bunkkis", "town": "Kyiv", "nation": "Ukraine", "rank": "Resident"},
    {"name": "_Azami695181", "town": "Kyiv", "nation": "Ukraine", "rank": "Resident"},
    {
        "name": "_DiscoDeer923654",
        "town": "Kyiv",
        "nation": "Ukraine",
        "rank": "Resident",
    },
    {"name": "_Technilu", "town": "Kyiv", "nation": "Ukraine", "rank": "Resident"},
    {
        "name": "_the_storm_guy_1",
        "town": "Kyiv",
        "nation": "Ukraine",
        "rank": "Resident",
    },
    {"name": "_Spotknot33", "town": "Kyiv", "nation": "Ukraine", "rank": "Resident"},
    {
        "name": "_SnaggyMedal3356",
        "town": "Punisher",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "_PlanetFarn11",
        "town": "Punisher",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Ikruka2227",
        "town": "Punisher",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Elka6821",
        "town": "Lipolia",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {"name": "meerkat714", "town": "soviet", "nation": "Russia", "rank": "Mayor"},
    {"name": "DepthianYT", "town": "soviet", "nation": "Russia", "rank": "Resident"},
    {"name": "DazzCazz23", "town": "soviet", "nation": "Russia", "rank": "Resident"},
    {
        "name": "Elijahh___",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "ke_i_prophet",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "yourgranny2332",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Legosponge923",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_Ender9872",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_Lgam3r1797",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "SteelingBison21",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "XDJakeXD145",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_Kye03x",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_ItzWaffel",
        "town": "New_Caledonia",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {"name": "XiaoFranco", "town": "LesPetits", "nation": "Teya", "rank": "Resident"},
    {
        "name": "Kellynda",
        "town": "LesPetits",
        "nation": "Teya",
        "rank": "Nation Leader",
    },
    {"name": "Deilyar", "town": "LesPetits", "nation": "Teya", "rank": "Resident"},
    {
        "name": "_Earthsuly",
        "town": "Queensland",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "_WilleMagasin",
        "town": "TheNoDrugCrib",
        "nation": "somalia",
        "rank": "Mayor",
    },
    {
        "name": "fireman0900",
        "town": "TheNoDrugCrib",
        "nation": "somalia",
        "rank": "Resident",
    },
    {
        "name": "Dustonus671",
        "town": "Grass",
        "nation": "Grass",
        "rank": "Nation Leader",
    },
    {"name": "TheRealSplitzy", "town": "Peru", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "_Diamond2551",
        "town": "Germania",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "deadlykiten11_",
        "town": "chuncheon",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "heycodyreid",
        "town": "wall",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {"name": "julijulita", "town": "Chile", "nation": "Chile", "rank": "Nation Leader"},
    {"name": "_InfernoZc7128", "town": "Chile", "nation": "Chile", "rank": "Resident"},
    {"name": "TTVM1chael", "town": "Chile", "nation": "Chile", "rank": "Resident"},
    {
        "name": "OolongFish",
        "town": "Beijing",
        "nation": "China",
        "rank": "Nation Leader",
    },
    {
        "name": "_Chaotix6382",
        "town": "East_Anglia",
        "nation": "NAJADE_Federation",
        "rank": "Mayor",
    },
    {
        "name": "Enderodakasu3",
        "town": "East_Anglia",
        "nation": "NAJADE_Federation",
        "rank": "Resident",
    },
    {
        "name": "_Aussie50987",
        "town": "home_home",
        "nation": "moscow",
        "rank": "Nation Leader",
    },
    {
        "name": "_PatukkaF",
        "town": "Tornio",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {"name": "RAMV0", "town": "Tampico", "nation": "Nueva_Castilla", "rank": "Mayor"},
    {
        "name": "LightEmotion",
        "town": "Trebizond",
        "nation": "Greater_Armenia",
        "rank": "Mayor",
    },
    {
        "name": "_Hailzk4",
        "town": "East_Coast_Haven",
        "nation": "New_Zealand",
        "rank": "Mayor",
    },
    {"name": "_SIyYT", "town": "Illinois", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "Lauren84",
        "town": "island",
        "nation": "Toronto",
        "rank": "Nation Leader",
    },
    {
        "name": "spacemonke9524",
        "town": "island",
        "nation": "Toronto",
        "rank": "Resident",
    },
    {"name": "_Kaelell", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "CourtDog328", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "bun_bunny__", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "Fredinator10", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "L0XT", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "piggyBeany", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "JohnnyPlayz8", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "_xfleur", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {
        "name": "_NormalBee695733",
        "town": "island",
        "nation": "Toronto",
        "rank": "Resident",
    },
    {"name": "_Ghxstleon", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "_billa8805", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "_Dius11", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "_Sfare2008", "town": "island", "nation": "Toronto", "rank": "Resident"},
    {"name": "95SS", "town": "AbuDhabi", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "AbuelitaProBR",
        "town": "AbuDhabi",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Trabestiscott",
        "town": "AbuDhabi",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "KissingZeHommies",
        "town": "Wahah",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "vMinerva", "town": "Los_Pilares", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "CerealIsASoup",
        "town": "Mt._Vernon",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "MoonMan8000",
        "town": "Mt._Vernon",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "NetheriteNuggett",
        "town": "Aqua_Kingdom",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "Domcza", "town": "Metov", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "_UniformPath8986",
        "town": "lolibra",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "warmbittersoup",
        "town": "Anchorage",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "PumpkinOppai",
        "town": "Anchorage",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Sheepio559",
        "town": "Anchorage",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_Gaycat9078507",
        "town": "Anchorage",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {"name": "Tyrin239", "town": "Tortel", "nation": "No Nation", "rank": "Mayor"},
    {"name": "Emilytg", "town": "Tortel", "nation": "No Nation", "rank": "Resident"},
    {"name": "mood__", "town": "Tortel", "nation": "No Nation", "rank": "Resident"},
    {
        "name": "DeathReaper_95",
        "town": "Tortel",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_Quinn_its_cool",
        "town": "norwich",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "kubek_z_herbata",
        "town": "LMAOburg",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "_lucabanana19",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Nation Leader",
    },
    {
        "name": "_Misslaurenuni",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Geminxi_7894",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "radio_music",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "lisenk1",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "Spongebob552",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "Asm_Larry",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Littleman69420",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "InfinityHydras3",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Vienepientje",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "JESSYORTOLA",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Teddie958256",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_GuiOr0612",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Josh_ETN",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_GdayGuys",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "DQ3",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "SweptGlobe78816",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "Its__Rxce",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_XkatelynX6568",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "Blulbie",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Noxyyyyy1371",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "SwatPvPanda",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_lettucevin",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "TheIdleRose",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "MrKoiBoi",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_DiiDii174",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "AbomasalPaper0",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "WdMdAd2018",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "veptics",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "DoctorFrizballz",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Faroshock",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "Cool_Cat02",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "SelfTaughtIdiot",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "vercitiies",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "PolskiDiamond",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_TheCamp19",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "Pineapplecat007",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_PithyWharf97408",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "AmyMay15",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "1KronosLevelUp",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "TheCustart",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "xFirezX",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "eeveekeeper",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Mees8163",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "Justin0575_",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "rinsp",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_Anysa0601",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "_chucklehead0401",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "John_Rawls",
        "town": "sunsetvalley",
        "nation": "Madagascar_C.U.L",
        "rank": "Resident",
    },
    {
        "name": "KMT_MrWang",
        "town": "Vladivostok",
        "nation": "East_Soviet_Union",
        "rank": "Nation Leader",
    },
    {
        "name": "DannyTheBoi",
        "town": "Vladivostok",
        "nation": "East_Soviet_Union",
        "rank": "Resident",
    },
    {
        "name": "Harry_Cooper49",
        "town": "Vladivostok",
        "nation": "East_Soviet_Union",
        "rank": "Resident",
    },
    {
        "name": "nathanp783",
        "town": "Vladivostok",
        "nation": "East_Soviet_Union",
        "rank": "Resident",
    },
    {
        "name": "socksoffonly",
        "town": "Assunpink",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "SuperIdolCjo", "town": "Paris", "nation": "Francia", "rank": "Resident"},
    {
        "name": "BxgsBqnny",
        "town": "Paris",
        "nation": "Francia",
        "rank": "Nation Leader",
    },
    {"name": "_Zzoomeray", "town": "Paris", "nation": "Francia", "rank": "Resident"},
    {"name": "_Mental6877", "town": "Paris", "nation": "Francia", "rank": "Resident"},
    {"name": "Lukasboy132", "town": "Paris", "nation": "Francia", "rank": "Resident"},
    {
        "name": "_UltPlayZzz",
        "town": "Saturday_Bambe",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "_Alan280128",
        "town": "Saturday_Bambe",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "StarIsNotStar",
        "town": "Rainbow_Star_Oasis",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "_DecSav16", "town": "Okinawa", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "_ColinBB_89",
        "town": "Okinawa",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "_Semjex18",
        "town": "Cirta-Numadia",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {"name": "Moonrush_", "town": "MT", "nation": "Russia", "rank": "Mayor"},
    {"name": "epikthecat", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "eviisamazing", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "_Gaymonkey187", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "_mutabuta513", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "_Sosiska3062", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "_Toastidius", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "Moon_Dear_b", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "_Chicken_bap12", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "_ShieldGaming951", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "MyCatisaPotato", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "_lanaquq14", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {"name": "_Da_Ghostz8293", "town": "MT", "nation": "Russia", "rank": "Resident"},
    {
        "name": "_Nico14mincre",
        "town": "Seattle",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "EngrahX",
        "town": "KocikDonerink",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "Bilx22",
        "town": "westen_ocean_city",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "_OranieTheCat",
        "town": "westen_ocean_city",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Buttershr00m",
        "town": "Saint_Valeria",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "sarahloux",
        "town": "Saint_Valeria",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "_MajesticCat1901",
        "town": "Saint_Valeria",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "RiiverSiide",
        "town": "Saint_Valeria",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "leahcaestecker",
        "town": "Saint_Valeria",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {"name": "_juanr0017112", "town": "pvp", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "xReiwaFx",
        "town": "UnbanSupruz",
        "nation": "4.2ReadRules",
        "rank": "Nation Leader",
    },
    {
        "name": "YunusKaraeski",
        "town": "UnbanSupruz",
        "nation": "4.2ReadRules",
        "rank": "Resident",
    },
    {"name": "gajxh", "town": "South_Sentineal", "nation": "Sundom", "rank": "Mayor"},
    {
        "name": "derUbootfahrer",
        "town": "Noxus",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "_Pokewide",
        "town": "Requiem",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "poke_wide",
        "town": "Requiem",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {"name": "10Lodzer71", "town": "Kibris", "nation": "No Nation", "rank": "Mayor"},
    {"name": "_Princette", "town": "Lazaelia", "nation": "No Nation", "rank": "Mayor"},
    {"name": "Krashnt", "town": "Quito", "nation": "Ecuador", "rank": "Nation Leader"},
    {"name": "zDepresiva_Gk", "town": "Quito", "nation": "Ecuador", "rank": "Resident"},
    {"name": "Windoss", "town": "Quito", "nation": "Ecuador", "rank": "Resident"},
    {"name": "SLATTMAS", "town": "Quito", "nation": "Ecuador", "rank": "Resident"},
    {
        "name": "2inTheStink",
        "town": "mining_retreat",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "taxxons",
        "town": "Underground_Embassy",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "AshPLee",
        "town": "Underground_Embassy",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Blossom8487",
        "town": "Underground_Embassy",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {"name": "Ghostinator", "town": "Flexarmy", "nation": "No Nation", "rank": "Mayor"},
    {"name": "_Jussinemo", "town": "tampere", "nation": "No Nation", "rank": "Mayor"},
    {"name": "Henemer", "town": "tampere", "nation": "No Nation", "rank": "Resident"},
    {
        "name": "_Jersku2010",
        "town": "tampere",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Cinnamon_r0ll",
        "town": "southampton",
        "nation": "Spanish_Republic",
        "rank": "Mayor",
    },
    {
        "name": "_Luigisspaghetti",
        "town": "southampton",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_giraffe1232641",
        "town": "southampton",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "Golems_",
        "town": "southampton",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "DailyEgg8099959",
        "town": "southampton",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_Homer3665",
        "town": "southampton",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "Piesel8178",
        "town": "southampton",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {
        "name": "_xrya6873",
        "town": "southampton",
        "nation": "Spanish_Republic",
        "rank": "Resident",
    },
    {"name": "_Ninjachems44", "town": "Rain", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "boy45acegame",
        "town": "ducks_happy",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {
        "name": "atrevido_1",
        "town": "ducks_happy",
        "nation": "No Nation",
        "rank": "Resident",
    },
    {
        "name": "Goatperson1",
        "town": "Sacramento",
        "nation": "No Nation",
        "rank": "Mayor",
    },
    {"name": "Baconiry", "town": "Croatia", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "Jalsku",
        "town": "NorthernLands",
        "nation": "Lapland",
        "rank": "Nation Leader",
    },
    {
        "name": "tyhamhisilisko",
        "town": "NorthernLands",
        "nation": "Lapland",
        "rank": "Resident",
    },
    {
        "name": "LyroxLux",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_liekeheyde",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "SparklesTR",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "MrStampyCatGD",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Nation Leader",
    },
    {
        "name": "_GoldHyperion895",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "KONNOSR",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Imogen300611",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "stand0",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_AnnaSoup555",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_KaeBee77527",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "goofyio",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_ManicBluePanic",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "kathiscoolswag",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_MintBicycle257",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_VanishedLion885",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Feldt_",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Namboo_",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "WrldOfGuz",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "calosmuguiro",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Knight_Ninja120",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_PaisleyMarker66",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Callum_bro4018",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "homegd",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "eforg",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_AntonDy08",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "greeksparti",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Mereltje17",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "SIPHOON_",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Imogenplayzxoxo",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Timi167",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_UNKNOWNBOI29",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Creeamyy",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Lietuvis2021",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Klamilo7031",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_RainbowEstey16",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_H0p3ful25",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_YamatoShobei",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_JunkosFan75",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Mohammad6634",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_CacoKiller21",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Goldmaedchen2010",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "PicAndPoc",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_distrutctor",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_RoseTen31602547",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Valeria2013",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Hendrik_C_R",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Annewestphal",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_BluishShark9338",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Tobias_croc10",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "rrreenie",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Unicornsquid002",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "gigi_honey",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_LiveScorpion778",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_AutumnAmoeba598",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "CURLZ6401",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_ayato0809121023",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_MGro21",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Taha61qt",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "1tofu1",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "Pianomaster123",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_crc383",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "_Merlin_moss",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {
        "name": "busch00000000",
        "town": "Vaygach_Island",
        "nation": "Severny",
        "rank": "Resident",
    },
    {"name": "DxffyDuck", "town": "Nicosia", "nation": "No Nation", "rank": "Mayor"},
    {
        "name": "_Gl00mxBunny",
        "town": "Kongsberg",
        "nation": "Norway",
        "rank": "Nation Leader",
    },
    {"name": "BennyBurst", "town": "Kongsberg", "nation": "Norway", "rank": "Resident"},
    {
        "name": "WafflStonks",
        "town": "Clearwater",
        "nation": "Northwest",
        "rank": "Nation Leader",
    },
    {
        "name": "Coktail",
        "town": "Clearwater",
        "nation": "Northwest",
        "rank": "Resident",
    },
    {
        "name": "_Weirdgamer001",
        "town": "Clearwater",
        "nation": "Northwest",
        "rank": "Resident",
    },
    {
        "name": "Humanhen",
        "town": "Clearwater",
        "nation": "Northwest",
        "rank": "Resident",
    },
    {
        "name": "DaddyDukaj",
        "town": "dog",
        "nation": "Riau_Islands",
        "rank": "Nation Leader",
    },
    {
        "name": "_MICHAELDUKAJ",
        "town": "dog",
        "nation": "Riau_Islands",
        "rank": "Resident",
    }
]
