li = [
    {
        "name": "Britan",
        "residents": [
            "isac__",
            "fjunior_0911",
            "ChromeCrits",
            "suuv",
            "Szymqn",
            "idk69420",
            "penqX",
            "Connexorr",
            "clappedcookie",
            "Blissterz",
            "Wagle13",
            "Brawlclick",
            "P1nk_B0y",
            "EgirlKotten",
            "MeezoidFiggy",
            "EchoStream",
            "G2_Vinny",
            "stuffybear21",
            "AirborneSaint03",
            "COVID_gang69",
            "bergerle",
            "Beanbag4eva",
            "3KHO",
        ],
        "towns": ["Who_Was_In_Paris", "birmingham", "Devon", "Market"],
        "king": "Wagle13",
        "capitalName": "Devon",
        "capitalX": -784,
        "capitalZ": -10312,
        "area": 255,
    },
    {
        "name": "lovozaro",
        "residents": ["ben013", "EtrnlEngineer", "Mr_Xbomx"],
        "towns": ["cherub"],
        "king": "ben013",
        "capitalName": "cherub",
        "capitalX": 7152,
        "capitalZ": -13944,
        "area": 92,
    },
]
